### ISSUE TITLE
Loading process on t-visne

### ISSUE THREAD

**Issue by TrentinErasmo** [angeloschatzimparmpas/t-viSNE#5]
Hi @angeloschatzimparmpas ,

I downloaded the code, the requirements you put on the file and google chrome as well on linux (ubuntu).
I followed your guide on the readme file, I open the browser and go to localhost:8000, but when I try to load a table or one of the dataset available, a windows opens loading and nothing happens. I attached a screenshot hoping this will help you to understand.

Thanks in advance,
Erasmo Trentin
![Screenshot](https://user-images.githubusercontent.com/65651468/115376526-0f2f6a80-a1cf-11eb-9b1a-8f09e4a2cb2b.png)

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

Actually, I believe there is no problem. **t-viSNE** simply needs time to **produce 500 projections in the backend** with the _Grid Search_ option. After the first time, it will be very fast because it caches the results from the initial execution, for each data set though. The _Single Set_ option uses the hyperparameters you provide with the sliders, and it is a much faster alternative.

What you can try first is to use the **Iris** instead of the **Diabetes** data set. Then, try the Diabetes data set but it will take a couple of minutes (up to 1-2 hours depending on the hardware of your computer) when using the _Grid Search_ option.

The following demonstration video could be useful to understand how t-viSNE works: https://vimeo.com/403858988

Please, let me know if it is all right after my feedback. Thank you for trying out our visual analytics tool.

Best regards,
Angelos Chatzimparmpas

**Comment by TrentinErasmo** [comment]
Hello @angeloschatzimparmpas ,

Unfortunately I left the tool for an entire night and day but it was still loading. I also tried the "single set" but when I click on "execute new tsne analysis"  nothing happens.
I checked if I downloaded in the right way the programs "frontend" ( I never used npm) but as you wrote on the readme file it should not be necessary.

Thanks for your help. Hope to be able to use this fantastic tool.

Best regards,
Erasmo Trentin

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

I think now I understand what is the problem. You are serving correctly the frontend, but not the backend.

You should use a new terminal/console and type the following command (in the main folder as with the frontend): FLASK_APP=tsneGrid.py flask run 
At the same time, you should keep serving the frontend, thus, you need two consoles/terminals open at the same time (see screenshot).
![t-viSNE_Running](https://user-images.githubusercontent.com/16924088/115687782-cf958980-a35a-11eb-9e00-978faa0074a9.png)

In case, you cannot observe that the backend is being served properly (check the screenshot above), you might need to install the modules that you are missing by using: pip install name_of_module
More details can be found also in the readme file. Hopefully, you have already executed the following command: 
pip install -r requirements.txt

Finally in macOS, I had to give permission when executing a new t-SNE analysis. Please, let me know if it worked with the new comments.

Best regards,
Angelos Chatzimparmpas

**Comment by TrentinErasmo** [comment]
Hello @angeloschatzimparmpas ,

After your instructions I noticed an error message on the shell you can see on the screenshot, so I tried to download again bhtsne using "pip install" and from the github page. Now it seems to work perfectly.

Thanks again for your help,
Erasmo
![Screenshot_1](https://user-images.githubusercontent.com/65651468/115720335-45125180-a37d-11eb-8ede-7e97f8b7b850.png)
![Screenshot_2](https://user-images.githubusercontent.com/65651468/115720341-46437e80-a37d-11eb-8e62-2ac5e21d7d6f.png)

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

I am glad everything works as expected. I will keep this issue for more people that might face similar problems.

I hope you enjoy using the tool.

All the best,
Angelos
