### ISSUE TITLE
Problems with SPECTF data set in GridSearch option 

### ISSUE THREAD

**Issue by TrentinErasmo** [angeloschatzimparmpas/t-viSNE#6]
Hello @angeloschatzimparmpas 

I was trying the datasets you gave in the github repository as examples, but when I try the SPECTF data set this message appears (see screenshot). If with the same data set I use the SingleSet option, it works.

The same happens when I try to analyze a csv file that I created. 

With Diabetes, Iris and BreastCancer datasets everything works perfectly.

Thanks again for your help,
Erasmo Trentin
![Screenshot](https://user-images.githubusercontent.com/65651468/116217407-e7e61980-a749-11eb-9f3f-d0fae4d60425.png)

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

I found the problem with the _Grid Search_ option for the _SPECTF_ data set. You have to go to line: **348** before the _else_ statement, and then add the following lines (for the _SPECTF_ data set):

        elif (label == 'Abnormal'):
            convertLabels.append(0)
        elif (label == 'Normal'):
            convertLabels.append(1)

**Please, check my screenshot.** You have to do something similar for your data set. 
If I remember correctly you should also use an asterisk (*) for the variable/attribute that should become the target class (or so-called class label).

Let me know if it worked.

All the best,
Angelos Chatzimparmpas

<img width="430" alt="Screenshot 2021-04-27 at 18 11 38" src="https://user-images.githubusercontent.com/16924088/116276230-9dce5980-a784-11eb-89c0-de8cddea43f8.png">

**Comment by TrentinErasmo** [comment]
Dear @angeloschatzimparmpas 

Thanks a lot, it worked!

Unfortunately, I noticed another problem, but I think it regards my screen resolution. As you can see in the first and second screenshots, I have to select a wider area in order to include all the points (there are also minor problems inside the light-blue circles where "remaining cost" and "density" symbols are cut). Moreover, in the third screenshot you can see how the "dimensions correlation" option does not work, and if I try to change the threshold a popup message appears, as if it doesn't receive the input of the second point in order to create the line (the same happens if I try to create a path with multiple points)
If it can help, my screen resolution is 1366x768 (15,6 inches)
![Screenshot_1](https://user-images.githubusercontent.com/65651468/116387814-7b3b4f80-a81b-11eb-9abb-ee09444475d9.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/65651468/116387817-7c6c7c80-a81b-11eb-9ee9-bf9b73176258.png)
![Screenshot_3](https://user-images.githubusercontent.com/65651468/116387818-7c6c7c80-a81b-11eb-9653-84adc97c082a.png)


Thanks again for your help,
Erasmo Trentin

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

Unfortunately, the first problems you encountered are indeed related to the resolution. I cannot do much except that you could check if zooming in/out is a bit helpful. To do that use your browser's functionality, but still, the problem may persist.

About the **Dimension Correlation**, you can try to increase the number of points you added to the screen; for example, instead of 2 anchor points, try to create a line with 3-4 segments, and then use right-click to confirm. I think the problem is that it does not read one of the points you placed in your projection due to the resolution issue.

Additionally, I suggest you change the "Correl." option from _Distance_ to _KNN_. Maybe this also helps. Then try different values from the slider below this field, and see if you can capture some points.

Let me know if something from the above solved your problem (at least partially).

Best regards,
Angelos

**Comment by TrentinErasmo** [comment]
Hello @angeloschatzimparmpas ,

Now it works perfectly (except for the resolution, I will try to change the screen).

Thanks again for your help,
Erasmo

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

Great, I am glad it worked. I hope all problems are solved after you use a larger screen.

I will keep this issue for more people that might face similar problems.

All the best,
Angelos C.

**Comment by angeloschatzimparmpas** [comment]
Hello @TrentinErasmo ,

Great, I am glad it worked. I hope all problems are solved after you use a larger screen.

I will keep this issue for more people that might face similar problems.

All the best,
Angelos C.
